id: 9cf438483dc5454e8ce971500495b63c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
  language: en
  author: ''
  volume: {}
